// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

float width;
float height;
int inBoundary;
RWTexture2D<float4> outputTexture;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if (inBoundary == 0)
    {
        outputTexture[id.xy] = float4(1.0, 0.0, 0.0, 1.0); // Red
    }
    else
    {
        outputTexture[id.xy] = float4(0.0, 0.0, 1.0, 1.0); // Blue
    }
}
